name: CI

on:
  push:
    branches: [1_tasks]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    name: Lint and test
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run lint
      - run: npm run test